API_PROXY:
  PROXY_HOST: 127.0.0.1
  PROXY_PORT: 1080
server:
  port: 6818

spring:
  profiles:
    active: dev

  task:
    scheduling:
      pool:
        size: 10
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/hyerp?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

    jpa:
      hibernate:
        ddl-auto=create: create

# mybatis 配置内容
mybatis:
  mapper-locations: classpath:mapper/*.xml # 配置 Mapper XML 地址
  type-aliases-package: com.hyerp.model # 配置数据库实体包路径

# Swagger配置
springfox:
  documentation:
    swagger-ui:
      enabled: true
      path: /swagger-ui.html
debug: false